---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        name:
          - git
          - ansible
          - htop
          - tmux
          - neovim
          - zsh
          - tree
          - python3
          - nodejs
          - jq
          - ipython3
          - ripgrep
          - exa
          - bat
          - dconf-cli
          - python3-psutil
          - meld

    - name: remove packages
      package:
        name:
          - nano
        state: absent


    # Dconf
    # to get all possible settings, use `dconf dump /`
    - name: copy wallpaper file
      copy:
        src: files/wallpaper.jpeg
        dest: /usr/share/backgrounds/ansible-wallpaper.jpeg
        owner: root
        group: root

    - name: set wallpaper
      become_user: adam
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpeg'"

    - name: set wallpaper position
      become_user: adam
      dconf:
        key: "/org/gnome/desktop/background/picture-options"
        value: "'zoom'"

    - name: copy tmux configuration
      copy:
        src: files/tmux.conf
        dest: /home/adam/.tmux.conf
        owner: adam
        group: adam

    - name: copy Zsh configuration
      copy:
        src: files/zshrc
        dest: /home/adam/.zshrc
        owner: adam
        group: adam

    - name: add automation user
      user:
        name: automation
        system: yes

    - name: set up sudo for automation user
      copy:
        src: files/sudoer_automation
        dest: /etc/sudoers.d/automation
        owner: root
        group: root
        mode: 0440

    - name: add ansible-pull cron job
      cron:
        name: ansible auto-provision
        user: automation
        minute: "*/10"
        job: >
          ansible-pull
          --only-if-changed
          --url https://github.com/AdamMartinCote/linux-config.git

    - name: set cap lock to control
      become_user: adam
      dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value:
          - "ctrl:nocaps"
