---
- hosts: localhost
  connection: local
  become: true

  tasks:
    - name: install packages
      package:
        name:
          - htop
          - tmux
          - neovim
          - zsh
          - tree
          - python3
          - node
          - jq
          - ipython3
          - ripgrep
          - exa
          - bat
